apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: role-rbac-write
  annotations:
    security.kubeapt.io/displayName: "Rbac Write"
    security.kubeapt.io/description: "Roles must not grant write/bind/escalate permissions on RBAC resources."
    security.kubeapt.io/resource: "Roles"
    security.kubeapt.io/severity: "9"
    security.kubeapt.io/remediation: "Remove write/bind/escalate on RBAC resources. Fields: rules[*].apiGroups, rules[*].resources, rules[*].verbs."
    security.kubeapt.io/product: "Kubernetes"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - rbac.authorization.k8s.io
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - roles
  variables:
  - name: rbacResources
    expression: |
      ["roles","rolebindings","clusterroles","clusterrolebindings"]
  - name: rbacWriteVerbs
    expression: |
      ["create","update","patch","delete","bind","escalate"]
  validations:
  - expression: |
      !has(object.rules) || object.rules.all(r,
        !(r.apiGroups.exists(ag, ag == "rbac.authorization.k8s.io") &&
          r.resources.exists(res, variables.rbacResources.exists(rr, rr == res)) &&
          r.verbs.exists(v, variables.rbacWriteVerbs.exists(rv, rv == v))
        )
      )
    message: |
      Roles must not grant write/bind/escalate permissions on RBAC resources.
